### ISSUE TITLE
ruby issue

### ISSUE THREAD

**Issue by trinib** [trinib/trinib#107]
https://github.com/trinib/word-cloud/issues/41#issue-1345589994
> Need some who knows ruby to fix
> 
> ```
> Run ruby <<- EORUBY
> To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
> /home/runner/work/word-cloud/word-cloud/wordcloud/octokit_client.rb:5:in `<class:OctokitClient>': uninitialized constant Octokit::Preview (NameError)
> 	from /home/runner/work/word-cloud/word-cloud/wordcloud/octokit_client.rb:3:in `<top (required)>'
> 	from /home/runner/work/word-cloud/word-cloud/wordcloud/runner.rb:5:in `require_relative'
> 	from /home/runner/work/word-cloud/word-cloud/wordcloud/runner.rb:5:in `<top (required)>'
> 	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
> 	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
> 	from -:1:in `<main>'
> Error: Process completed with exit code 1.
> ```

**Comment by trinib** [comment]
fixed https://github.com/trinib/word-cloud/issues/41#issuecomment-1229452756
